# Generated by Django 4.2.5 on 2023-10-03 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0004_remove_order_being_delivered_remove_order_received_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='id',
            new_name='id_category',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='id',
            new_name='id_Item',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='id',
            new_name='id_order',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='id',
            new_name='id_orderItem',
        ),
        migrations.RenameField(
            model_name='slide',
            old_name='id',
            new_name='id_slide',
        ),
    ]
