# Generated by Django 4.2.5 on 2023-10-03 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0007_alter_orderitem_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='item',
            new_name='item1',
        ),
    ]
